### ISSUE TITLE
⚠️ This action has a security risk! Release source/change diff is obfuscated

### ISSUE THREAD

**Issue by frenck** [sarisia/actions-status-discord#364]
SSIA

Ref: <https://github.com/sarisia/actions-status-discord/compare/v1.10.0...v1.10.1>

This seems weird, there is no way to validate what it is in this upgrade from a technical and security perspective. I've currently closed all dependabot upgrade requests because of it.

../Frenck

**Comment by sarisia** [comment]
Hi @frenck ,

Nice catch! And thank you for letting me know the security concerns.

I've introduced the new release workflow which uses [@vercel/ncc](https://github.com/vercel/ncc) to build and
[JasonEtco/build-and-tag-action](https://github.com/JasonEtco/build-and-tag-action) to push release commit + tags
since v1.10.0.

This improves the action's performance and also my release procedure a lot, but since
the release commit now only contains the built attifact and removes all the source codes,
getting diff from release tag to another release tag may not work as expected. (you'll see
the "Automatic compilation" commit from github-actions[bot], which has huge diffs)

![image](https://user-images.githubusercontent.com/33576079/201960283-2d7317b1-683f-441d-8f4c-62511758486a.png)

Now I've improved the release workflow a bit, added ways to get the correct changelogs and also validate
the built artifacts:

- Source codes are now tagged with `-src` suffix.
  - e.g. for changes between `v1.10.0` and `v1.10.1`, we can do https://github.com/sarisia/actions-status-discord/compare/v1.10.0-src...v1.10.1-src
- We can now check the GitHub Actions workflow run from release's commit message

  ![image](https://user-images.githubusercontent.com/33576079/201963671-16c3604c-597b-4b08-92f2-e90a9617fc54.png)

- We can also check that the release commit is created within the workflow run above by checking the signed commit
  
  ![image](https://user-images.githubusercontent.com/33576079/201964145-8dafb997-fc69-4b95-af34-21309329e586.png)

Hope this helps, and if you have any concerns, please feel free to let me know.

**Comment by frenck** [comment]
I don't think it is a solution. The performance benefits are very minimal.

GitHub Actions have massive security concerns; not being able to see the ran code directly, is a big no-go for larger projects (including projects I'm working on).

There is no guarantee your `-src` branch is matching what I'm running.

**Comment by frenck** [comment]
The just released v1.10.2 impose the exact same security issue. The source code is obfuscated. 

See: <https://github.com/sarisia/actions-status-discord/blob/v1.10.2/lib/index.js>

**Comment by frenck** [comment]
> I'm still not sure what's the matter with you.

Why do you make this personal? That is low imho.

**Comment by sarisia** [comment]
I'm sorry, I did not mean to offend you and I made a mistake in word choice.

Let me clarify, I really want to make things better but still cannot understand what is lacking and how to fix it.

**Comment by frenck** [comment]
> Furthermore, this is an OSS project so if you cannot trust the released artifacts, feel free to fork this repo and build on your own.

One can never "trust" third-party code in that sense. Especially when security tokens are involved (in this case, this action uses a webhook that should be kept a secret).

Therefore, a review of the code is a way to determine if the change can be trusted (and also doesn't impose a breaking change for one use case). However, it has been obfuscated.

I think forking is counterproductive for the foss community to solve problems. I rather see the foss community work together and all use and work on the same sources. That is way more powerful than having little difference spread everywhere. I'm somewhat surprised to read about the offered solution.

I indeed see this as a weird recommendation by an official action template maintained by GitHub. I've reached out to GitHub and GitHub security for a statement/comment on that part, as they basically recommend shipping obfuscated code.

../Frenck

**Comment by sarisia** [comment]
> Therefore, a review of the code is a way to determine if the change can be trusted (and also doesn't impose a breaking change for one use case). However, it has been obfuscated.

Yes, I agree to this but I want to say that a review should be happened against the source code, not the
build artifact, so I think whether the build artifact is minified (obfuscated) or not has nothing to do with
security. If the bundler (compiler) and supply chains, including locked dependencies and release
workflows, are considered safe, the safety of the build artifact can be guaranteed.

Same can be said to other compiler languages, such as Golang and Java, etc. We hardly review
the output binaries and reviewing source codes are cosidered sufficient.

To summarize the current situation, we have 2 points:

### 1. The build artifact is minified (obfuscated)

Fixing this is easy. Just stop using `ncc`'s `--minify` option to go.
But as I stated above, this has nothing to do with security I think.

Also, while the official template uses `ncc` without minifying, many popular
actions adds minifying options by themselves. (e.g. [peaceiris/actions-gh-pages](https://github.com/peaceiris/actions-gh-pages),
[docker/login-action](https://github.com/docker/login-action))
I'm still not sure which is the best practice.

### 2. Cannot get the diff between the build to build

This is because [JasonEtco/build-and-tag-action](https://github.com/JasonEtco/build-and-tag-action)
creates the commit which only contains the build artifact and removes all the source codes.

Fixing this means stop using this action, so I need some time to find the alternative way to do this,
including semantic-versioned tagging, pushing artifact, etc.

Also, I'm using [JasonEtco/build-and-tag-action](https://github.com/JasonEtco/build-and-tag-action) because
[the GitHub Docs](https://docs.github.com/en/actions/creating-actions/releasing-and-maintaining-actions#setting-up-github-actions-workflows) recommends using this and now I'm not sure this is the best practice or not.

**Comment by sarisia** [comment]
> https://github.com/sarisia/actions-status-discord/issues/364#issuecomment-1317041783
> I indeed see this as a weird recommendation by an official action template maintained by GitHub. I've reached out to GitHub and GitHub security for a statement/comment on that part, as they basically recommend shipping obfuscated code.

@frenck sorry for ping you, but did you get any response from GitHub security?

**Comment by frenck** [comment]
Nope, nor did anything happen here. Closing the issue as I don't expect change or progress. Meanwhile, it keeps showing up in "my open issues list."

Oh! Before I forget: Happy New Year 🥂 

../Frenck

**Comment by sarisia** [comment]
Got it, thanks!

Also I'm planning to add the GitHub Actions build log to the release assets and it is tracked in #394 .

Happy new year to you too! 🎉
